version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'drowssap'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  auth:
    build:
      dockerfile: Dockerfile
      context: ./auth-microservice
    volumes:
      - ./auth-microservice:/app
    ports: 
      - "8096:8096"
  login:
    build:
      dockerfile: Dockerfile
      context: ./login-microservice
    volumes:
      - ./login-microservice:/app
    ports: 
      - "8080:8080"
  products:
    build:
      dockerfile: Dockerfile
      context: ./products-microservice
    volumes:
      - ./products-microservice:/app
    ports:
      - "8081:8081"
  checkout:
    build:
      dockerfile: Dockerfile
      context: ./checkout-microservice
    volumes:
      - ./checkout-microservice:/app
    ports:
      - "8082:8082"
  app:
    build:
      dockerfile: Dockerfile
      context: ../ecommerce-web-app
    volumes:
      - ../ecommerce-web-app
    ports:
      - "8090:8090"
volumes:
  my-db:


